-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 22:14:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gym_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gym_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym_app` DEFAULT CHARACTER SET utf8 ;
USE `gym_app` ;

-- -----------------------------------------------------
-- Table `gym_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_app`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `dateBirth` DATE NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `session` TINYINT NULL,
  `secret_token` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_app`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_app`.`articles` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `img` VARCHAR(355) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) ,
  INDEX `fk_articles_users_idx` (`users_id` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
